[cursor]
style = "Beam"


[font]
size = 10.0

[font.normal]
family = "Hack NF"
style = "Bold"



[window]
startup_mode = "Windowed"
opacity = 0.8
dynamic_title = true

[window.padding]
x = 8
y = 10

[shell]
program = "pwsh.exe"
